### ISSUE TITLE
Fix the User Guide stub

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#101]
https://cfde-published-documentation.readthedocs-hosted.com/en/latest/about/portalguide/ (https://github.com/nih-cfde/published-documentation/blob/stable/docs/about/portalguide.md) is the temporary destination for the "User Guide" in the CFDE portal. They have to figure out how to render it directly, so it lives here until then. 

I made a title only stub so I could give them a link to put in the portal, we just need to fill it in. The content for it is here: https://docs.google.com/document/d/1S5ll51sKuFuV3uzCQrCZM_y23nqevP55x42guhAsuOI/edit#heading=h.d8xnrwtm93r

So no writing to do, just need to markdownify it. It's 100% okay if we lose some features, as long as it stays functional. So, we don't care about the title page, or the TOC or the version or the formatting just the useful content. 

Don't change the filename! that will break the link they're putting in the portal. Need this at least first pass done for Tuesday at the cross pollination. It's okay if it's a little rough, we can fix more after, but it needs to have more than just a title if people click on it.

**Comment by fridayek** [comment]
@jeremywalter I finished updating the User Guide. It is currently a GoogleDoc in this folder: https://drive.google.com/drive/folders/1ds3BEg5YwUf0oYgXoWRN-1GzA-Vug7xx 

If you need it in markdown, it may be easier for you to convert it in GoogleDocs using Add-ons > Docs to Markdown > Convert from the menu bar. The markdown text then needs to be copied and pasted wherever you plan on housing it. I just converted it myself, but I don't know where to copy and paste it.

Please let me know if you have any questions.

**Comment by ACharbonneau** [comment]
thanks @fridayek

**Comment by RLC-DCPPC** [comment]
Hi @jeremywalter, how is the proceeding? If I understand, you are converting this to Markdown?

**Comment by jeremywalter** [comment]
Hi @RLC-DCPPC @fridayek, the Markdown is about ready to go, but I still need the images to add to the repo.

**Comment by jeremywalter** [comment]
@ACharbonneau is anything else needed here?
