### ISSUE TITLE
new web address

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#115]
We're moving all the sites to be in the same domain. 

This one is going to be docs.nih-cfde.org

Need someone in @nih-cfde/training to work out how we do a custom domain in RTD, preferably with either keeping the original address working or having some kind of redirect that keeps the original from just showing a 404.

I've got a bit of code in [this PR](https://github.com/nih-cfde/use-case-library-build/pull/38) that can be reused to tell people that the site is moving/has moved  if we want that.

The new address doesn't quite exist yet, but lets get it figured out asap before we have a bunch of site users.

issue where new address is being made:
https://github.com/nih-cfde/use-case-library-build/issues/35#issuecomment-725491836

**Comment by s-canchi** [comment]
These are the steps that need to happen to update the published document website to **docs.nih-cfde.og** :
- Add a CNAME record from _6b02efc61b7b129933a3494f422ba999.docs.nih-cfde.org to _verify2775588f.domains.readthedocs.com to verify ownership of your domain.
- Wait for SSL certificate issuance and domain configuration (this may take a few days).
- Add a CNAME record in your DNS pointing your custom domain to 2775588f.domains.readthedocs.com.

@victor73 Could you help with the DNS end of verification ?
