### ISSUE TITLE
Need to rename specifications-and-documentation

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#129]
Arthur has requested that we rename https://github.com/nih-cfde/specifications-and-documentation to https://github.com/nih-cfde/c2m2

I will do the actual rename because it needs admin privileges, but in order to do the rename:

- [x] The [readme for this repo](https://github.com/nih-cfde/published-documentation) needs to be updated 
- [x] the [readme for specifications-and-documentation](https://github.com/nih-cfde/specifications-and-documentation) needs to be updated
- [x] the bot code for [releases](https://github.com/nih-cfde/published-documentation/blob/dev/.github/action-release-drafter.yml) needs to be updated
- [x] the bot code for [autogenerating previews](https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/update_specs_preview.yml) needs to be updated
- [x] the bot code for [autogenerating pulls to stable](https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/update_specs_stable.yml) needs to be updated
- [ ] need to update branch names in RTD
- [x] need to rename repo
- [x] need to update branch protection rules
- [x] need to change the repos it pulls from in .gitmodules

@nih-cfde/training

**Comment by s-canchi** [comment]
I can help with the code and readme update if those don't require admin powers.

**Comment by ACharbonneau** [comment]
Hey @s-canchi do you have an estimate for when you'll have the changes ready?

**Comment by abradyIGS** [comment]
Friendly nudge: It would be concretely helpful to me if we could get this rename resolved quickly: I'm about to start building an entire Epic's worth of tasks centered on this repo, and the name will be super confusing to many of the eyes it's about to draw if it's still labeled as a general documentation bin.

**Comment by s-canchi** [comment]
All tasks are done. The changes are currently in a PR in both the repo's. Once merged they should reflect the new changes.

**Comment by ACharbonneau** [comment]
Getting this actually working:

- had to fix a bunch of missed references to specs in PRs
- had to change the gitmodules file
- had to locally respawn the repo to make it change submodules. website can't handle that operation

**Comment by ACharbonneau** [comment]
This is done, and I think I've fixed the lingering problem with the bot not making previews
