### ISSUE TITLE
mini tutorial: how to reject a submission

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#174]
@nih-cfde/training 

If there is already a 'how to approve' this could be mostly a copy paste of that, but it would be nice for this to have it's own wiki page so it's easy to find

**Comment by marisalim** [comment]
the 'how to approve' mini tutorial is here https://github.com/nih-cfde/published-documentation/wiki/How-to-approve-your-datapackage

assuming rejecting a submission means changing the DCC Approver Status to "content rejected", I can add a wiki pg for this.

**Comment by marisalim** [comment]
mini tutorial for rejecting submission here - https://github.com/nih-cfde/published-documentation/wiki/How-to-reject-a-submission

closing issue, but let me know here if something should be fixed!
