### ISSUE TITLE
HMP submission people

### ISSUE THREAD

**Issue by mgiglio99** [nih-cfde/published-documentation#177]
Hello,
Here is the list of HMP people and the roles they should have.
https://docs.google.com/spreadsheets/d/1ukoJPiZKgR_qPJ8pSa3XbzjMFSNOPrlRy09YHhi1coc/edit?usp=sharing
Thanks,
Michelle

**Comment by jeremywalter** [comment]
Onboarded - not sure on process so leaving open for further submissions if needed.

**Comment by ACharbonneau** [comment]
link it to the onboarding issue and close
