### ISSUE TITLE
grammar in privacy policy needs help

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#253]
specifically references to CFDE and CFDE-CC are confusing

**Comment by ACharbonneau** [comment]
> This is a very very trivial point that likely nobody cares about but me (and yet here I am mentioning it) but I think there’s some minor grammatical funkiness in the privacy policy whereby “CFDE” is defined as CFDE-CC plus affiliates (i.e., a plural noun) but then “CFDE” is sometimes treated as a plural noun (“The CFDE also collect…“) but more often as a singular noun (“The CFDE collects…“). Perhaps some of the latter is due to the conflation of CFDE-CC with CFDE but I don’t think that’s true in every case.

**Comment by kinsingc** [comment]
Thank you for raising this, Amanda, I also care.

I tend to refer to CFDE the program as a singular noun.  CFDE awardees/entities/centers/partners would all be treated as a plural.

Also, the word, “data”, is the plural form of datum.

Chris
