### ISSUE TITLE
C2M2_datapackage.json accessibility

### ISSUE THREAD

**Issue by jeremyjyang** [nih-cfde/published-documentation#314]
According to the OSF Example C2M2 submission datasets (https://osf.io/uadny/), "we've also included the master JSON Schema file describing the full C2M2 system (C2M2_datapackage.json)", but according to the "Recent Activity", this C2M2 master JSON Schema was removed on 2021-12-08. How can this file, as updated for current C2M2 compliance, now be accessed?

**Comment by ACharbonneau** [comment]
@abradyIGS can you update that link to the correct one

**Comment by abradyIGS** [comment]
@jeremyjyang that was a floating copy that was obsolesced -- the permanent link to the current master copy is higher up in the hierarchy at https://osf.io/c63aw/ -- sorry for being confusing.

**Comment by abradyIGS** [comment]
I have updated the descriptive text on the OSF node -- it used to have several subcollections of files; it now contains only the stub-TSV fileset; the root-level desc was stale and described more contents than were available; fixed now.
