### ISSUE TITLE
Documentation for Q4

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/published-documentation#346]
A list of docs that should be updated for Q4. In particular, and user-visible UI changes should be accounted for.

We'll work with @fridayek to get updates incorporated.

**Comment by RLC-DCPPC** [comment]
@mschor, @jrchudy : please chime in with updates based on what you've done for Q4.

**Comment by lliming** [comment]
The submission review page (for data submitters) now has a new section called "Metadata Connectivity" that shows FAIR assessment results.

**Comment by DavidMichaelKelly** [comment]
For cfde-submit, I've make these changes to the docs within the past month or so:

- new section about installing git
- add info about the --dry-run flag
- how to upgrade cfde-submit

**Comment by lliming** [comment]
The profile page (pull down name in upper-right corner, click "My Profile") will sometimes have dbGaP study IDs.  The "sometimes" is pretty complicated, though.  
(1) Only if the logged-in person logged in using "eRA Commons" (as opposed to Google, campus login, etc.)
(2) Only if the logged-in person actually has been granted permission to any dbGaP studies.

**Comment by fridayek** [comment]
I met with @jrchudy yesterday and he informed me the changes for this release include the below items. I will update the User Guide documentation accordingly.

No changes to homepage
  - icons might change next week with 3 new ones when Mike comes back
Dashboard
  - personal collections widget
    - can click through each one to the record page
    - bug fixes to show empty collections to add to on load
    - files picker opens facet panel
  - favorites moved down
    - larger text
    - new favorites
      - analysis type, phenotype, protein*
Review page
  - fair metrics display graph
Profile
  - RAS permissions viewable (if user has any)
File
  - “export to cavatica” - export menu option called NCPI manifest

**Comment by jonathancrabtree** [comment]
Closing lest there be confusion with Q4 2023.
