### ISSUE TITLE
cfde-submit tool documentation

### ISSUE THREAD

**Issue by jeet-vora** [nih-cfde/published-documentation#352]
The cfde-submit tool requires git package to work. A note can be added for DCCs to ensure git is installed in their system for cfde-submit to execute.
https://docs.nih-cfde.org/en/latest/cfde-submit/docs/

**Comment by ACharbonneau** [comment]
@DavidKelly999 Can you add this to your submit docs please?

**Comment by jonathancrabtree** [comment]
Note was added last April. Closing.
