### ISSUE TITLE
broken header

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/published-documentation#372]
i broke the header in some recent commits #369 #370 #371

https://docs.nih-cfde.org/en/latest/

![Screen Shot 2022-04-29 at 10 06 23 AM](https://user-images.githubusercontent.com/7544197/165990931-ef599c4e-ef01-437f-ba2f-b246c3669a83.png)

**Comment by raynamharris** [comment]
these are the previews from the. last working update https://github.com/nih-cfde/published-documentation/pull/361
and a recent not working update https://github.com/nih-cfde/published-documentation/pull/369

notice the capitalization page titles

![Screen Shot 2022-04-29 at 11 55 44 AM](https://user-images.githubusercontent.com/7544197/166008662-41d9d971-69d6-471c-82f3-5887eddc6a99.png)
![Screen Shot 2022-04-29 at 11 55 50 AM](https://user-images.githubusercontent.com/7544197/166008667-8de0a162-a417-4929-a9fa-6bf5ff1c92db.png)

**Comment by ctb** [comment]
```
mamba create -n cfde-pub-doc python=3.9
conda activate cfde-pub-doc

# make sure you're on latest stable branch, then
pip install -r requirements.txt

git submodule init
git submodule update

mkdocs build
```
produces a `site/index.html` that shows the broken header.

**Comment by ctb** [comment]
Reverting mkdocs-material to 6.2.6 in requirements.txt like so:
```
-mkdocs-material==8.2.11
+mkdocs-material==6.2.6
```
fixes things for me locally.

**Comment by ctb** [comment]
This requirement was updated by @ACharbonneau per https://github.com/nih-cfde/published-documentation/commit/e13380b355187627223b50b3c300e0337458f84b.

:spreads hands and looks around expectantly:

**Comment by raynamharris** [comment]
might work locally but it doesn't work with the automatic build 

https://github.com/nih-cfde/published-documentation/pull/374

**Comment by raynamharris** [comment]
fixed currently by ignoring the-fair-cookbook/content/recipes/Discoverability/seo.ipynb

**Comment by raynamharris** [comment]
okay, still kinda broken in that the banner doesn't appear and you have to click the 3 bars (which was broken before). however, now things are building successfully again. a ipynb file was ignored

**Comment by raynamharris** [comment]
looks great in the build 

![Screen Shot 2022-05-02 at 10 56 36 AM](https://user-images.githubusercontent.com/7544197/166299654-7bee9a75-3fd0-4781-b414-b9ea4f0ef114.png)

build in chrome looks like this 

![Screen Shot 2022-05-02 at 10 57 40 AM](https://user-images.githubusercontent.com/7544197/166299779-d64b45e1-463a-4181-8671-f94f1bbca22a.png)

in safari looks great!

![Screen Shot 2022-05-02 at 10 58 18 AM](https://user-images.githubusercontent.com/7544197/166299869-a06bba39-5c17-430b-a5e2-9940b28f3f91.png)

**Comment by raynamharris** [comment]
nevermind! all good. maybe just needed to refresh :)


![Screen Shot 2022-05-02 at 11 05 08 AM](https://user-images.githubusercontent.com/7544197/166300846-2216e776-d4a9-4c55-91cc-cfb8d0a784b9.png)
)
