### ISSUE TITLE
DRS not a valid persistent_id based on the current specification

### ISSUE THREAD

**Issue by u8sand** [nih-cfde/published-documentation#382]
Current guidance seems to be a move towards the use of [GA4GH DRS](https://github.com/ga4gh/data-repository-service-schemas) URIs for persistent_ids, to the point that a bug was reported with the persistent_id assertion which did not report DRS URIs as satisfying the persistent_id criterion (See https://github.com/MaayanLab/appyter-catalog/issues/798).

However as per https://docs.nih-cfde.org/en/latest/c2m2/draft-C2M2_specification/#c2m2-identifiers
> To be used as a C2M2 persistent_id, an ID
> 1. will represent an explicit commitment by the managing DCC that the attachment of the ID to the resource it represents is **permanent and final**
> 2. must be a format-compliant [URI](https://tools.ietf.org/html/rfc3986) or a [compact identifier](https://n2t.net/e/compact_ids.html), where the protocol (the "scheme" or "prefix") specified in the ID is registered with at least one of the following (see the given lists for examples of URIs and compact identifiers)
>    - the IANA ([list of registered schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml))
>        - scheme used must be assigned either "Permanent" or "Provisional" status
>    - Identifiers.org ([list of registered prefixes](https://registry.identifiers.org/registry))
>    - N2T (Name-To-Thing) ([list of registered prefixes](https://n2t.net/e/n2t_full_prefixes.yaml))
> 3. if representing a file, an ID used as a persistent_id cannot be a direct-download URL for that file: it must instead be an identifier permanently attached to the file and only indirectly resolvable (through the scheme or prefix specified within the ID) to the file itself

Though DRS URIs may satisfy conditions 1 and 3, DRS are not registered in IANA, identifiers.org, or N2T and thus do not satisfy the conditions to be a valid persistent_id.

If the use of DRS *specifically* is desired, the persistent_id guidelines should be updated. Additionally, if it is expected that data can be resolved through DRS for the purpose of data resolution in cloud workbenches, then perhaps scoping the persistent_id even further would be in order; otherwise a completely valid persistent_id, like a DOI would not be compatible with all of the future platform features.

**Comment by ctb** [comment]
thanks @u8sand - my hot take (that no one asked for ;) is that we should change persistent_id to explicitly be DRS-resolvable. Unfortunately, since the DRS specification is ~evolving, this is still a bit wibbly, but there's no solution for that. In effect the practical statement is "this should be something DRS-compliant workbenches can use to import the underlying data."

**Comment by owhite** [comment]
@u8sand -- on the bi-weekly call I believe you said one issue was that this meant that your FAIR metrics report these persistent_IDs as non-compliant / not passing. Can you give more detail on that?

**Comment by u8sand** [comment]
@owhite As DRS are not valid `persistent_id`s by the C2M2 docs, the appyter reports them as not valid, correctly so.

But it seems we're being encouraged to use DRS identifiers for persistent_ids in the C2M2 for CAVATICA-driven resolution among other things. If DRS ids are desired, then the C2M2 should be updated accordingly before the appyter can report compliance with the C2M2 when a DRS identifier is used in the persistent_id field.

**Comment by abradyIGS** [comment]
> If the use of DRS specifically is desired, the persistent_id guidelines should be updated.

[Done](https://docs.nih-cfde.org/en/latest/c2m2/draft-C2M2_specification/index.html#c2m2-identifiers). Added text to condition 2:

> * protocols not appearing in the above registries but explicitly approved by the CFDE-CC. Currently, this list is limited to one protocol, namely drs:// URIs identifying [GA4GH Data Repository Service](https://github.com/ga4gh/data-repository-service-schemas) resources. 

> if it is expected that data can be resolved through DRS for the purpose of data resolution in cloud workbenches, then perhaps scoping the persistent_id even further would be in order; otherwise a completely valid persistent_id, like a DOI would not be compatible with all of the future platform features.

This functionality is not _currently_ generally expected of persistent IDs, nor is it expected of DRS IDs in the general case. As of right now we will be using a selected subset of DRS ID values to demonstrate cloud workbench integration, but the conditions as stated are (now) fully in line with design expectations.

As for the proposal to reduce the space of `persistent_id` values to only DRS URIs, and possibly to restrict them further to only those URIs which afford (e.g.) automatable/workbench-importable file resolution, I have no objection and will await a decision before doing further definition updates. I believe this to be feasible (and probably useful to boot); we'll need to inventory existing IDs and carefully assess consequences, but I don't anticipate any major problems given current metadata.
