### ISSUE TITLE
Portal and Dashboard User Guide is out of date

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/published-documentation#403]
The main issue here is that the dashboard graphs no longer have a "Stack by" option, due to [dashboard issue 144](https://github.com/nih-cfde/dashboard/issues/144). Both the documentation and screenshots should be updated accordingly.

**Comment by jeremywalter** [comment]
https://github.com/nih-cfde/published-documentation/blob/jeremy-updates/docs/about/portalguide.md#filter-the-chart

**Comment by jeremywalter** [comment]
Here is where the old documentation starts to break and needs updating: https://github.com/nih-cfde/published-documentation/blob/stable/docs/about/portalguide.md#filter-the-chart -- perhaps all that is needed is removal of the 'stacked' image and mentions of stack along with some updating for the variables (Scale vs Stacked).

**Comment by jeremywalter** [comment]
portalguide.md had an extensive re-write and update of images for new terms and organization, if more changes are needed, please review and create a new issue
