### ISSUE TITLE
glossary links wrong

### ISSUE THREAD

**Issue by jimmymathews** [nih-cfde/published-documentation#75]
Currently, in the C2M2 Model Documentation you see at
[https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/C2M2-usage-guides-and-technical-documents/000-INTRODUCTION/)](https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/C2M2-usage-guides-and-technical-documents/000-INTRODUCTION/)
the terms in the paragraphs which are links to the glossary end up at a dummy version of the glossary, e.g.:
[https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/CFDE-glossary/#c2m2-instance](https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/CFDE-glossary/#c2m2-instance)

However, the direct 'Glossary' link takes you to:
[https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/CFDE-glossary-test/](https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/CFDE-glossary-test/)
which, despite the name ('-test'), is actually the right one, with actual term definitions.

I think there is a mixup about the naming of the glossary location, 'CFDE-glossary-test' points to the right one and 'CFDE-glossary' points to a test one.

Update: Created a pull request with a simple fix. #76

**Comment by ACharbonneau** [comment]
Will be fixed by combination of  #77 and https://github.com/nih-cfde/the-fair-cookbook/pull/39
