### ISSUE TITLE
FAIR cookbook rendering duplications

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#96]
https://github.com/nih-cfde/the-fair-cookbook/issues/52

(this issue can be closed in 2 other places when complete)

- may need to add .pages to published docs to get the naming of the fair cookbook navbar tab right + need to edit path to intro.md in the published docs index.md file (might need to be a separate PR in this repo)

**Comment by marisalim** [comment]
cookbook TOC render issues fixed on website now
