### ISSUE TITLE
Need a release plan

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#97]
Could I get you to do a mini release plan thing for here too. I put a little info in https://github.com/nih-cfde/published-documentation/blob/dev/README.md let me know if you need other info

**Comment by s-canchi** [comment]
The current release plan version for this site only includes information for  tags and documentation. The only dates I have for releases are from our training website which were originally based on the NIH deliverables. Would it make sense to add those dates here ?

**Comment by ACharbonneau** [comment]
no set dates for this one. just release notes please. And it would be great if they could be auto-tagged with whether they were updates from the cookbook, the specs and docs repo, or the main repo.

**Comment by s-canchi** [comment]
The release notes will now have separate headings for the different PRs based on originating repo. I used the labels included in the GitHub actions for creating PRs. However, I noticed the title of the PR is hardcoded in the action file leading to a generic "Auto update ...." title for all the PRs. These will be mapped to the release notes as is and I am not sure how useful it might be.

**Comment by ACharbonneau** [comment]
hmm. I'm not sure this is a sane thing to do, but we could maybe try to make the action pull the PR title from the corresponding PR in the submodule? that assumes that all the submodules are making useful PR messages tho, which is likely hard to enforce. I think for now I'm not too worried about it. If you want to try to figure out a fancy fix at some point we can, but for now I guess I'll just had do the release notes?

**Comment by s-canchi** [comment]
That might be worth looking into and I can poke around a bit more on it. For now you will get a draft of the release notes for all PRs merged into `dev` and `stable`. 
A point of clarification regarding the branch names. Are the PRs for this repo structure similar to the training repo with merge into `dev` followed by `stable` ? While the changes from FAIR and specs repo are directly merged into `stable`. On the PRs for the submodule updates however it states merged into `master`. Is `master` == `stable` ?

**Comment by ACharbonneau** [comment]
there are 2 actions for each submodule. One merges changes to preview, the other merges them to stable. in THIS REPO we only have stable (not master), and it is the branch that displays the website. For both the submodules I am pulling from *their* master branches. 

If anything in *this* repo still says master it should be updated. Please either make a PR with the fix or make an issue that points me at the specific places I missed. 

Since we're pulling changes from other people, the 'dev' branch for changes in a submodule is effectively master there. The dev branch here is just for updates to this repo. I'm not sure how to better explain that...it makes sense if you draw it :)

**Comment by s-canchi** [comment]
That explanation makes things clearer. I guess I was a bit confused by [some of these recent PRs](https://github.com/nih-cfde/published-documentation/pull/94) which were related to the submodule update which says merge into `master`. One point to note is that I have to test the release automation after it is merged. Because of this repo's special structure I was not able to test on a forked repo.

**Comment by ACharbonneau** [comment]
Heh. Those were 6 whole days ago. Back in the old days when this repo had a master branch.

**Comment by s-canchi** [comment]
In that case the PR is good to be merged and I can revisit it to ensure the automation works correctly.
