### ISSUE TITLE
Good review of README

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#98]
I needed to get the last PR done because the website was broken without it. Now I'd love it if someone(s) could help me make sure my instructions page makes sense

https://github.com/nih-cfde/published-documentation/blob/dev/README.md

and any other comments/edits :)

**Comment by abhijna** [comment]
On it. Is this on the ASAP timeline?

**Comment by ACharbonneau** [comment]
No. This is just an ongoing maintenance thing

**Comment by marisalim** [comment]
do you want the readme info to be added to the website's Contributing doc?

**Comment by ACharbonneau** [comment]
We aren't taking CFDE documentation submissions from outside the CFDE.
