### ISSUE TITLE
The change fetching robot is still broken for specs and docs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#99]
The specifications-and-documentation repo is private. 

For the [continuous integration robot](https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/ci.yml) having it use cfde-bots ALLTHEACTIONS credential make it work, but it didn't work in the update workflows:

- https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/update_cookbook_preview.yml
- https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/update_cookbook_stable.yml
- https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/update_specs_preview.yml
- https://github.com/nih-cfde/published-documentation/blob/dev/.github/workflows/update_specs_stable.yml

The action that is breaking is [actions/checkout@v2](https://github.com/actions/checkout). It only sort of can do private submodules. See: https://github.com/actions/checkout/issues/287

My current attempt at a solution was from https://github.com/actions/checkout/issues/116#issuecomment-583790750 but clearly didn't work.

In those issues, there is also a suggestion about using SSH keys. cfde-bot has an SSH key as a secret called `RTDprivaterepo` if you want to try that route.

**Comment by ACharbonneau** [comment]
hmm. update cookbook stable is working. the other three are not. maybe i just have some kind of typo?

**Comment by ACharbonneau** [comment]
It's just the specifications-and-documentation auth that's not working now. 

```
Run git -c "http.extraheader=Authorization: basic ***" submodule update --init --recursive --remote docs/specifications-and-documentation
Submodule 'docs/specifications-and-documentation' (git@github.com:nih-cfde/specifications-and-documentation.git) registered for path 'docs/specifications-and-documentation'
Cloning into '/home/runner/work/published-documentation/published-documentation/docs/specifications-and-documentation'...
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:nih-cfde/specifications-and-documentation.git' into submodule path '/home/runner/work/published-documentation/published-documentation/docs/specifications-and-documentation' failed
Failed to clone 'docs/specifications-and-documentation'. Retry scheduled
Cloning into '/home/runner/work/published-documentation/published-documentation/docs/specifications-and-documentation'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:nih-cfde/specifications-and-documentation.git' into submodule path '/home/runner/work/published-documentation/published-documentation/docs/specifications-and-documentation' failed
Failed to clone 'docs/specifications-and-documentation' a second time, aborting
Error: Process completed with exit code 1.
```

I wonder if I can literally give it the same code as the CI.

**Comment by ACharbonneau** [comment]
Good news: scoped CI code seems to work. Bad news: apparently the PR action is about to stop working https://github.com/nih-cfde/published-documentation/runs/1364822556?check_suite_focus=true

**Comment by ACharbonneau** [comment]
Also, it thinks that the submodule hasn't updated but it has.

**Comment by marisalim** [comment]
this is the part that is going to be deprecated - https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by ACharbonneau** [comment]
yeah I already fixed that

**Comment by ACharbonneau** [comment]
currently trying https://ehlers.berlin/blog/private-submodules-in-github-ci/
